#!/bin/bash

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /bin/mountpoint    /bin/
copy_exec /usr/bin/pv        /bin/
copy_exec /usr/bin/tr        /bin/
copy_exec /bin/head          /bin/
copy_exec /sbin/sfdisk       /sbin/
copy_exec /sbin/mkfs         /sbin/
copy_exec /usr/sbin/chpasswd /sbin/
copy_exec /usr/bin/eject     /sbin/
copy_exec /sbin/wipefs       /sbin/
copy_exec /usr/bin/lsblk     /bin/

# overwrite busybox binaries
copy_exec /bin/cpio          /mbin/
copy_exec /bin/tar           /mbin/
copy_exec /usr/bin/xz        /mbin/
copy_exec /bin/gzip          /mbin/
copy_exec /bin/umount        /mbin/
copy_exec /sbin/mke2fs       /mbin/

# kernel modules
manual_add_modules efivarfs
manual_add_modules nls-ascii
