#!/bin/bash

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/mountpoint /bin/mountpoint
copy_exec /usr/bin/pv         /bin/pv
copy_exec /usr/bin/tr         /bin/tr
copy_exec /usr/bin/head       /bin/head
copy_exec /usr/sbin/sfdisk    /sbin/sfdisk
copy_exec /usr/sbin/mkfs      /sbin/mkfs
copy_exec /usr/sbin/chpasswd  /sbin/chpasswd
copy_exec /usr/bin/eject      /sbin/eject
copy_exec /usr/sbin/wipefs    /sbin/wipefs
copy_exec /usr/bin/lsblk      /bin/lsblk

# overwrite busybox binaries
copy_exec /usr/bin/cpio       /mbin/cpio
copy_exec /usr/bin/tar        /mbin/tar
copy_exec /usr/bin/xz         /mbin/xz
copy_exec /usr/bin/gzip       /mbin/gzip
copy_exec /usr/bin/umount     /mbin/umount
copy_exec /usr/sbin/mke2fs    /mbin/mke2fs

# kernel modules
manual_add_modules efivarfs
manual_add_modules nls-ascii
